name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Run backend tests
        run: |
          docker-compose run backend python manage.py test

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker tag foodgram-backend ${{ secrets.DOCKER_HUB_USERNAME }}/foodgram-backend:${{ github.sha }}
          docker tag foodgram-front ${{ secrets.DOCKER_HUB_USERNAME }}/foodgram-front:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/foodgram-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/foodgram-front:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/deploy/foodgram
            git pull origin main
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
            docker image prune -f